default: all

problem1:
	gcc -lpthread problem1.c -o problem1

problem2:
	gcc -lpthread problem2.c -o problem2

all: problem1 problem2

clean:
	rm -f problem1 problem2

.PHONY: all show clean ps pdf showps
